apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../crd
  - ../rbac
  - ../manager
  - ../webhook

labels:
  - pairs:
      app.kubernetes.io/name: maas-controller
      app.kubernetes.io/component: maas-controller
      app.kubernetes.io/part-of: models-as-a-service

configMapGenerator:
  - name: maas-parameters
    envs:
      - params.env

replacements:
  - source:
      kind: ConfigMap
      name: maas-parameters
      fieldPath: data.MAAS_CONTROLLER_IMAGE
    targets:
      - select:
          kind: Deployment
          name: maas-controller
        fieldPaths:
          - spec.template.spec.containers.[name=manager].image
